version: 0.2
phases:
  pre_build:
    commands:
      - echo Copying .env.main into .env
      - cp .env.main .env
      - echo Installing node modules
      - npm install
artifacts:
  files:
    - '**/*'